server:
  servlet:
    context-path: /crud
  port: 80
  tomcat:
    uri-encoding: utf-8
spring:
  messages:
    basename: i18n/login
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true